# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Digital Analysis of Syriac Handwriting
#email: your-email@example.com
description: >- # this means to ignore newlines until "url:"
  DASH: Digital Analysis of Syriac Handwriting
url: https://dash.stanford.edu/ # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
#twitter_username: jekyllrb
#github_username: jekyll

# Build settings
source: src
markdown: kramdown
exclude:
  - assets/main.scss  # processed by webpack instead of Jekyll
  - assets/img/HMML-background-image_JPG.jpg  # written into main.css as a base64-encoded data uri
  - assets/fonts/syriac_fonts.css  # incorporated into main.css
  - assets/bundle.js  # in case it's left there from a previous (pre-webpack update) build

keep_files:  # all these files are built and/or copied to the _site/ folder by webpack
  - assets/bundle.js
  - assets/main.css
  - mirador
  # these are favicon and PWA-manifest files
  - android-chrome-192x192.png
  - android-chrome-512x512.png
  - apple-touch-icon.png
  - browserconfig.xml
  - favicon.ico
  - favicon-16x16.png
  - favicon-32x32.png
  - mstile-70x70.png
  - mstile-144x144.png
  - mstile-150x150.png
  - mstile-310x150.png
  - mstile-310x310.png
  - safari-pinned-tab.svg
  - site.webmanifest
